language: node_js
node_js:
  - "6.1"
  - "5.11"
  - "4.4"
before_script:
  - npm install
script:
  - npm run lint
  - npm test
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
